import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Footer } from '@/components/Footer';
import Header from '@/components/Header';
import { ToastContainer } from 'react-toastify';
import "react-toastify/dist/ReactToastify.css"
import StoreProvider from '@/components/StoreProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <StoreProvider>
          {children}
        </StoreProvider>
        <ToastContainer
         position='bottom-right'
         autoClose={5000}
         closeOnClick
         draggable
         />
        <Footer />
      </body>
    </html>
  );
}
